//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BugList
    {
        public int buglistid { get; set; }
        public string bugurl { get; set; }
        public string bugtype { get; set; }
        public string bugdesc { get; set; }
        public string bugnotes { get; set; }
    }
}
