//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies_ListDeleted
    {
        public int companyid { get; set; }
        public Nullable<int> listid { get; set; }
        public string name { get; set; }
        public string addr1 { get; set; }
        public string addr2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string weburl { get; set; }
        public string phone { get; set; }
        public string notes { get; set; }
    }
}
