//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosting
    {
        public int jobid { get; set; }
        public string jobtitle { get; set; }
        public string jobdescr { get; set; }
        public string jobstate { get; set; }
        public string jobcity { get; set; }
        public string contactemail { get; set; }
        public string contactphone { get; set; }
        public Nullable<System.DateTime> datestamp { get; set; }
        public string postedby { get; set; }
        public Nullable<int> companyid { get; set; }
        public string jobinfo { get; set; }
        public string contactname { get; set; }
    }
}
