//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpenJobs5
    {
        public int jobid { get; set; }
        public string jobtitle { get; set; }
        public string jobdescr { get; set; }
        public string jobcity { get; set; }
        public Nullable<System.DateTime> datestamp { get; set; }
        public string postedby { get; set; }
        public string status { get; set; }
        public Nullable<System.Guid> jobguid { get; set; }
        public string submittals { get; set; }
    }
}
