//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resume
    {
        public int resid { get; set; }
        public string lname { get; set; }
        public string fname { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string resume1 { get; set; }
        public Nullable<System.DateTime> resdt { get; set; }
        public string jobtitle { get; set; }
        public string jobloc { get; set; }
        public Nullable<int> jobloc1 { get; set; }
        public Nullable<int> jobloc2 { get; set; }
        public Nullable<int> jobloc3 { get; set; }
    }
}
