//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public int TrackingId { get; set; }
        public string DateInvoicePrice { get; set; }
        public string ClientContact { get; set; }
        public string DirectoryUP { get; set; }
        public Nullable<System.DateTime> DatePaid { get; set; }
        public Nullable<System.DateTime> RenewalReminder { get; set; }
        public string StaffAndTrainUP { get; set; }
        public Nullable<System.Guid> ListGuid { get; set; }
        public Nullable<System.Guid> CompanyGuid { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
