//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingDocument
    {
        public int TrainingDocumentLinkID { get; set; }
        public string TrainingDocumentName { get; set; }
        public string TrainingDocumentLink { get; set; }
        public string TrainingDocumentComments { get; set; }
        public string ShowLink { get; set; }
        public Nullable<int> TrainingDocumentOrder { get; set; }
    }
}
