//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProspectingList
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string listid { get; set; }
    
        public virtual UserProspectingList UserProspectingList1 { get; set; }
        public virtual UserProspectingList UserProspectingList2 { get; set; }
    }
}
