//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Security
    {
        public string loginid { get; set; }
        public string password { get; set; }
        public string userlevel { get; set; }
        public int companyid { get; set; }
        public string companyname { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string zip { get; set; }
        public string primarycontact { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string fax { get; set; }
        public string notes { get; set; }
        public Nullable<System.DateTime> datesignedup { get; set; }
        public string postedby { get; set; }
        public Nullable<bool> SingleCityPostings { get; set; }
        public string website { get; set; }
    }
}
