//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffandTrain.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class WhiteBoardName
    {
        public int WBId { get; set; }
        public string WhiteBoardName1 { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<bool> AllowRecruiter { get; set; }
    }
}
